name: Greetings
on: [issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Greet issue author
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "🎉 Welcome to the project, @${{ github.event.issue.user.login }}! Thank you for your contribution! 🚀"
            })
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
